// Hero mascot loops (F3): `npm run mascot`.
//
// Reads content/art/mascot/takes.json (each Higgsfield take, and which idle and
// celebration take the app uses), then:
//   1. downloads any raw take missing from content/.cache/mascot/,
//   2. encodes every take to content/art/mascot/takes/<take>.mp4: 480 px square
//      H.264 with no sound, the background brought back to the paper colour and
//      the repeated last frame dropped so it loops cleanly,
//   3. copies the two takes in use to public/mascot/idle.mp4 and celebrate.mp4,
//      each with its first frame as a WebP poster (also the reduced-motion still),
//   4. writes public/mascot/concha.webp, the still for the empty screens, from
//      the concha's cutout (content/art/cast/concha-cutout.webp),
//   5. writes content/art/mascot/takes.html, a page for watching the takes.
// Rules: docs/design.md, "Art", "Decided in F3". No Higgsfield calls: takes are
// generated by hand (see the F3 notes) and added to takes.json.

import { execFileSync, spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ffmpegPath from "ffmpeg-static";
import sharp from "sharp";
import { CLIP_SIZE, STILL_SIZE, backgroundGains, checkTakes, gainFilter, loopSeconds, probe } from "./mascot.mjs";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const ART = path.join(ROOT, "content", "art", "mascot");
const CACHE = path.join(ROOT, "content", ".cache", "mascot");
const TAKES = path.join(ART, "takes");
const PUBLIC = path.join(ROOT, "public", "mascot");
const CUTOUT = path.join(ROOT, "content", "art", "cast", "concha-cutout.webp");

const record = JSON.parse(readFileSync(path.join(ART, "takes.json"), "utf8"));
checkTakes(record);
for (const dir of [CACHE, TAKES, PUBLIC]) mkdirSync(dir, { recursive: true });

const kb = (file) => `${(statSync(file).size / 1024).toFixed(1)} KB`;

function ffmpeg(args) {
  const run = spawnSync(ffmpegPath, ["-hide_banner", "-v", "error", "-y", ...args], { encoding: "utf8" });
  if (run.status !== 0) throw new Error(`ffmpeg failed: ${run.stderr.trim().split("\n").slice(-3).join(" ")}`);
}

/** The first frame of a clip, scaled to `size`, as raw RGB. */
function firstFrame(file, size, filter) {
  const vf = [filter, `scale=${size}:${size}:flags=lanczos`].filter(Boolean).join(",");
  return execFileSync(ffmpegPath, ["-v", "error", "-i", file, "-vf", vf, "-frames:v", "1", "-f", "rawvideo", "-pix_fmt", "rgb24", "-"], {
    maxBuffer: 64 * 1024 * 1024,
  });
}

async function download(take, file) {
  const response = await fetch(take.url);
  if (!response.ok) throw new Error(`Could not download ${take.name}: ${response.status}`);
  writeFileSync(file, Buffer.from(await response.arrayBuffer()));
}

async function encode(take) {
  const raw = path.join(CACHE, `${take.name}.mp4`);
  if (!existsSync(raw)) await download(take, raw);
  const banner = spawnSync(ffmpegPath, ["-hide_banner", "-i", raw], { encoding: "utf8" }).stderr;
  const { duration, fps } = probe(banner);
  const gains = backgroundGains(firstFrame(raw, CLIP_SIZE), CLIP_SIZE);
  const out = path.join(TAKES, `${take.name}.mp4`);
  ffmpeg([
    "-i", raw,
    "-t", loopSeconds(duration, fps).toFixed(3),
    "-vf", `${gainFilter(gains)},scale=${CLIP_SIZE}:${CLIP_SIZE}:flags=lanczos`,
    "-an",
    "-c:v", "libx264", "-profile:v", "main", "-pix_fmt", "yuv420p", "-crf", "27", "-preset", "slow",
    "-movflags", "+faststart",
    out,
  ]);
  console.log(`${take.name}: ${duration.toFixed(2)} s at ${fps} fps, gains ${gains.map((g) => g.toFixed(3)).join(" ")}, ${kb(out)}`);
  return out;
}

async function poster(clip, file) {
  const rgb = firstFrame(clip, CLIP_SIZE);
  await sharp(rgb, { raw: { width: CLIP_SIZE, height: CLIP_SIZE, channels: 3 } }).webp({ quality: 80 }).toFile(file);
}

const encoded = new Map();
for (const take of record.takes) encoded.set(take.name, await encode(take));

for (const kind of ["idle", "celebrate"]) {
  const clip = path.join(PUBLIC, `${kind}.mp4`);
  copyFileSync(encoded.get(record.use[kind]), clip);
  await poster(clip, path.join(PUBLIC, `${kind}.webp`));
  console.log(`public/mascot/${kind}.mp4: ${record.use[kind]}, ${kb(clip)}; poster ${kb(path.join(PUBLIC, `${kind}.webp`))}`);
}

// The still: fitted with a 4% margin, as the card stills are (F2).
const inner = Math.round(STILL_SIZE * 0.92);
const figure = await sharp(CUTOUT).resize(inner, inner, { fit: "inside" }).toBuffer();
const still = path.join(PUBLIC, "concha.webp");
await sharp({ create: { width: STILL_SIZE, height: STILL_SIZE, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
  .composite([{ input: figure, gravity: "center" }])
  .webp({ quality: 82 })
  .toFile(still);
console.log(`public/mascot/concha.webp: ${kb(still)}`);

// The takes page: each take as the app shows it, on the menu's paper and on a white card.
const row = (take) => {
  const inUse = Object.entries(record.use).find(([, name]) => name === take.name)?.[0];
  return `<figure><div class="pair"><div class="paper"><video src="takes/${take.name}.mp4" autoplay loop muted playsinline></video></div><div class="white"><video src="takes/${take.name}.mp4" autoplay loop muted playsinline></video></div></div><figcaption><b>${take.name}</b> · ${take.model}${inUse ? ` · <em>in use (${inUse})</em>` : ""}</figcaption></figure>`;
};
writeFileSync(
  path.join(ART, "takes.html"),
  `<!doctype html>
<meta charset="utf-8">
<title>Mascot takes</title>
<style>
  body { font: 16px system-ui, sans-serif; background: #fff8ec; color: #2b2340; margin: 24px; }
  main { display: flex; flex-wrap: wrap; gap: 24px; }
  .pair { display: flex; gap: 8px; }
  .paper, .white { padding: 8px; border-radius: 16px; }
  .white { background: #fff; border: 2px solid #eee4d4; }
  video { width: 160px; height: 160px; display: block;
    mask-image: radial-gradient(closest-side, #000 80%, transparent);
    -webkit-mask-image: radial-gradient(closest-side, #000 80%, transparent); }
</style>
<h1>Mascot takes</h1>
<p>Generated by <code>npm run mascot</code> from <code>takes.json</code>. To use another take, change <code>use</code> in takes.json and run <code>npm run mascot</code> again.</p>
<main>
${record.takes.map(row).join("\n")}
</main>
`,
);
console.log(`content/art/mascot/takes.html: ${record.takes.length} takes`);
