// Hand-made corrections to the lemma list, for frequent forms it gets wrong
// or cannot know. Each key is a form from the frequency list. The value is the
// word it counts towards, `{ word: share }` to split it, or null to leave it out.
//
// Function words are kept as the words a learner meets: the article el takes
// la, los and las, but the pronouns lo, le, la-as-pronoun stay with lo and le;
// esto and eso are their own words, not forms of este and ese.

const fold = (word, forms) => Object.fromEntries(forms.map((f) => [f, word]));

export const OVERRIDES = {
  // Articles.
  ...fold("el", ["el", "la", "los", "las"]),
  ...fold("un", ["un", "una", "unos", "unas"]),
  // Pronouns.
  ...fold("lo", ["lo"]),
  ...fold("le", ["le", "les"]),
  ...fold("me", ["me"]),
  ...fold("te", ["te"]),
  ...fold("se", ["se"]),
  ...fold("nos", ["nos"]),
  ...fold("él", ["él"]),
  ...fold("ella", ["ella"]),
  ...fold("ellos", ["ellos", "ellas"]),
  ...fold("nosotros", ["nosotros", "nosotras"]),
  ...fold("usted", ["usted"]),
  ...fold("ustedes", ["ustedes"]),
  ...fold("yo", ["yo"]),
  ...fold("tú", ["tú"]),
  ...fold("mí", ["mí"]),
  ...fold("ti", ["ti"]),
  // Possessives and demonstratives.
  ...fold("mi", ["mi", "mis"]),
  ...fold("tu", ["tu", "tus"]),
  ...fold("su", ["su", "sus"]),
  ...fold("mío", ["mío", "mía", "míos", "mías"]),
  ...fold("tuyo", ["tuyo", "tuya", "tuyos", "tuyas"]),
  ...fold("suyo", ["suyo", "suya", "suyos", "suyas"]),
  ...fold("nuestro", ["nuestro", "nuestra", "nuestros", "nuestras"]),
  ...fold("este", ["este", "esta", "estos", "estas", "éste", "ésta", "éstos", "éstas"]),
  ...fold("ese", ["ese", "esa", "esos", "esas", "ése", "ésa", "ésos", "ésas"]),
  ...fold("aquel", ["aquel", "aquella", "aquellos", "aquellas"]),
  ...fold("esto", ["esto"]),
  ...fold("eso", ["eso"]),
  ...fold("aquello", ["aquello"]),
  ...fold("ello", ["ello"]),
  // Words that the lemma list only knows as forms of a verb or of another
  // word, and that are almost always the word itself.
  ...fold("como", ["como"]),
  ...fold("nada", ["nada"]),
  ...fold("para", ["para"]),
  ...fold("sobre", ["sobre"]),
  ...fold("entre", ["entre"]),
  ...fold("gracias", ["gracias"]),
  ...fold("así", ["así"]),
  ...fold("aún", ["aún"]),
  ...fold("dos", ["dos"]),
  ...fold("adelante", ["adelante"]),
  ...fold("arriba", ["arriba"]),
  ...fold("abajo", ["abajo"]),
  ...fold("encima", ["encima"]),
  ...fold("acerca", ["acerca"]),
  ...fold("apenas", ["apenas"]),
  ...fold("demasiado", ["demasiado", "demasiada", "demasiados", "demasiadas"]),
  ...fold("primero", ["primero", "primera", "primer", "primeros", "primeras"]),
  ...fold("segundo", ["segundo", "segunda", "segundos"]),
  ...fold("cara", ["cara", "caras"]),
  ...fold("música", ["música"]),
  ...fold("bomba", ["bomba", "bombas"]),
  ...fold("carretera", ["carretera"]),
  ...fold("pareja", ["pareja", "parejas"]),
  ...fold("línea", ["línea", "líneas"]),
  ...fold("política", ["política"]),
  ...fold("derecha", ["derecha"]),
  ...fold("izquierda", ["izquierda"]),
  ...fold("nota", ["nota", "notas"]),
  ...fold("calma", ["calma"]),
  ...fold("fecha", ["fecha"]),
  // Past participles used mostly as nouns or adjectives.
  ...fold("cuidado", ["cuidado"]),
  ...fold("comida", ["comida", "comidas"]),
  ...fold("marido", ["marido", "maridos"]),
  ...fold("llamada", ["llamada", "llamadas"]),
  ...fold("divertido", ["divertido", "divertida", "divertidos", "divertidas"]),
  ...fold("abogado", ["abogado", "abogada", "abogados"]),
  ...fold("salida", ["salida", "salidas"]),
  ...fold("entrada", ["entrada", "entradas"]),
  ...fold("cansado", ["cansado", "cansada", "cansados", "cansadas"]),
  ...fold("casado", ["casado", "casada", "casados"]),
  ...fold("soldado", ["soldado", "soldados"]),
  ...fold("encantado", ["encantado", "encantada"]),
  ...fold("herido", ["herido", "herida", "heridos", "heridas"]),
  ...fold("enamorado", ["enamorado", "enamorada", "enamorados"]),
  ...fold("mercado", ["mercado"]),
  ...fold("privado", ["privado", "privada"]),
  ...fold("mirada", ["mirada"]),
  ...fold("resultado", ["resultado", "resultados"]),
  ...fold("complicado", ["complicado", "complicada"]),
  ...fold("helado", ["helado"]),
  ...fold("ocupado", ["ocupado", "ocupada", "ocupados"]),
  ...fold("aburrido", ["aburrido", "aburrida"]),
  ...fold("interesado", ["interesado", "interesada"]),
  ...fold("pescado", ["pescado"]),
  ...fold("preocupado", ["preocupado", "preocupada", "preocupados"]),
  ...fold("equivocado", ["equivocado", "equivocada"]),
  ...fold("asustado", ["asustado", "asustada"]),
  ...fold("embarazada", ["embarazada"]),
  ...fold("muerto", ["muerto", "muerta", "muertos", "muertas"]),
  estado: { estar: 0.85, estado: 0.15 },
  pasado: { pasar: 0.6, pasado: 0.4 },
  pasada: { pasar: 0.3, pasado: 0.7 },
  sentido: { sentir: 0.5, sentido: 0.5 },
  querido: { querer: 0.5, querido: 0.5 },
  querida: "querido",
  vestido: { vestir: 0.3, vestido: 0.7 },
  partido: { partir: 0.3, partido: 0.7 },
  debido: { deber: 0.5, debido: 0.5 },
  jurado: { jurar: 0.5, jurado: 0.5 },
  parecido: { parecer: 0.5, parecido: 0.5 },
  cerrado: { cerrar: 0.5, cerrado: 0.5 },
  dormido: { dormir: 0.5, dormido: 0.5 },
  // Verb forms that are also a rarer noun or adjective.
  ...fold("ser", ["son", "era", "eras"]),
  sé: "saber",
  ...fold("decir", ["dije", "dicho"]),
  ...fold("mirar", ["mira"]),
  ...fold("pasar", ["pasa", "pase"]),
  ...fold("valer", ["vale"]),
  ...fold("esperar", ["espera"]),
  ...fold("ver", ["visto", "ves"]),
  ...fold("dejar", ["deja", "dejo"]),
  ...fold("escuchar", ["escucha"]),
  ...fold("haber", ["haya", "hayas"]),
  ...fold("llamar", ["llama"]),
  ...fold("tomar", ["toma", "tomo"]),
  ...fold("hablar", ["habla"]),
  ...fold("tratar", ["trata"]),
  ...fold("amar", ["amo", "ama"]),
  ...fold("quedar", ["queda", "quedo"]),
  ...fold("bastar", ["basta"]),
  ...fold("pensar", ["pienso"]),
  ...fold("llevar", ["lleva"]),
  ...fold("acabar", ["acabo"]),
  ...fold("hacer", ["haz"]),
  ...fold("volver", ["vuelto"]),
  ...fold("lamentar", ["lamento"]),
  ...fold("dar", ["dan", "date", "des"]),
  ...fold("salir", ["sal", "salga"]),
  ...fold("jurar", ["juro"]),
  ...fold("tener", ["ten"]),
  ...fold("alegrar", ["alegro", "alegra"]),
  ...fold("buscar", ["busca"]),
  ...fold("traer", ["traído"]),
  ...fold("llegar", ["llegue"]),
  ...fold("tocar", ["toca"]),
  ...fold("resultar", ["resulta"]),
  ...fold("escribir", ["escrito"]),
  ...fold("ganar", ["gana"]),
  ...fold("mandar", ["mando"]),
  ...fold("pagar", ["paga"]),
  ...fold("leer", ["leo", "leído"]),
  ...fold("costar", ["cuesta"]),
  ...fold("matar", ["mata"]),
  ...fold("sacar", ["saca"]),
  ...fold("rogar", ["ruego"]),
  ...fold("descubrir", ["descubierto"]),
  ...fold("caer", ["caído"]),
  ...fold("ir", ["vete", "vayas"]),
  // Short imperatives with a pronoun, which the dictionary lists as words.
  ...fold("dar", ["dame", "dale"]),
  ...fold("decir", ["dime", "dile"]),
  ...fold("hacer", ["hazlo"]),
  hecho: { hacer: 0.7, hecho: 0.3 },
  vino: { venir: 0.8, vino: 0.2 },
  vaya: { ir: 0.5, vaya: 0.5 },
  fuera: { fuera: 0.5, ser: 0.5 },
  oído: { oír: 0.6, oído: 0.4 },
  recuerdo: { recordar: 0.6, recuerdo: 0.4 },
  vivo: { vivir: 0.5, vivo: 0.5 },
  paso: { pasar: 0.5, paso: 0.5 },
  falta: { faltar: 0.6, falta: 0.4 },
  puesto: { poner: 0.7, puesto: 0.3 },
  trato: { tratar: 0.5, trato: 0.5 },
  odio: { odiar: 0.8, odio: 0.2 },
  traje: { traer: 0.6, traje: 0.4 },
  deseo: { desear: 0.5, deseo: 0.5 },
  intento: { intentar: 0.6, intento: 0.4 },
  muestra: { mostrar: 0.7, muestra: 0.3 },
  cuento: { contar: 0.6, cuento: 0.4 },
  pago: { pagar: 0.5, pago: 0.5 },
  roto: { romper: 0.6, roto: 0.4 },
  vista: { ver: 0.5, vista: 0.5 },
  lista: { lista: 0.5, listo: 0.5 },
  ...fold("ser", ["eres"]),
  ...fold("sentir", ["siento"]),
  ...fold("creer", ["creo", "crees", "cree"]),
  ...fold("deber", ["debe", "debes"]),
  ve: ["ir", "ver"],
  // Spellings of one word.
  ...fold("solo", ["solo", "sólo"]),
  ...fold("más", ["más", "mas"]),
  ...fold("quizás", ["quizás", "quizá"]),
  // Other words the lemma lists get wrong.
  ...fold("señorita", ["señorita", "señoritas"]),
  ...fold("desgraciado", ["desgraciado", "desgraciada", "desgraciados"]),
  ...fold("varios", ["varios", "varias"]),
  ...fold("destino", ["destino"]),
  ...fold("veras", ["veras"]),
  parís: null,
  // Vosotros and vos are not taught (see "Size, variant, grammar").
  vosotros: null,
  vosotras: null,
  os: null,
  vos: null,
};

/**
 * Words left out of the list even though the dictionary has them: letters,
 * names and English words that subtitles are full of.
 */
export const DROP = ["i", "uh", "york", "ben", "jane"];
